<div style="font-family: arial; padding: 30px; padding-bottom: 0;">

<h4 style="text-align: center;">In the Name of God</h4>

<h2 style="text-align: center; color: #103bc9;">CS232 - Advanced Programming</h2>

<h3 style="text-align: center; color: #d42c06;">Iran University of Science and Technology</h3>

<h3 style="text-align: center; color: #d42c06;">School of Mathematics and Computer Science</h3>

<h4 style="padding-top: 7px; text-align: center;">Winter-Spring 2024</h4>

<hr style="margin-top: 25px; border-color: #fff;">

<h1 style="text-align: center; color: #9c0000;">Chapter 2: Python Fundamentals</h1>

<h3 style="padding-top: 7px; text-align: center;">Sahar Pourghasemi, Mehrnoosh Mofidi
</h3>

<hr style="margin-top: 25px; border-color: #fff;">

</div>

<div style="font-family: arial; padding: 30px; padding-top: 15px; padding-bottom: 0;">

<hr style="margin-top: 25px; border-color: #fff;">

<h2 style="text-align: center; color: #186e00;">Section 15: numpy </h2>

<hr style="margin-top: 25px; border-color: #fff;">

</div>

<div style="font-size: 1.1em: arial; padding: 30px; padding-top: 0; padding-bottom: 0;">
    
<h2 id="introduction" style="color: #d42c06;">numpy
</h2>

</div>

<div style="font-size: 1.1em; font-family: arial; padding: 30px; padding-top: 0; padding-bottom: 0;">

<h4>numpy introduction</h4>


<span>NumPy is a powerful Python library for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently.</span>


</div>

In [4]:
import numpy as np
import pandas as pd

<div style="font-size: 1.1em; font-family: arial; padding: 30px; padding-top: 0; padding-bottom: 0;">

<h4>numpy arrays</h4>


<span>NumPy arrays are homogeneous, meaning they can only contain elements of a single data type. Some commonly used data types in NumPy include integers , floating-point numbers , and booleans. The attribute of a NumPy array gives information about the data type of its elements.</span>


</div>

In [ ]:
arr = np.array([1, 2, 3], dtype=float)
print(arr.dtype)

<div style="font-size: 1.1em; font-family: arial; padding: 30px; padding-top: 0; padding-bottom: 0;">

<h4>numpy random seed</h4>


<span>NumPy's random module allows us to generate random numbers. By setting the random seed, we can ensure that we get the same random numbers every time we run the code.</span>


</div>

In [3]:
np.random.seed(42)
arr = np.random.randint(0, 10, size=5)
print(arr)

[6 3 7 4 6]


<div style="font-size: 1.1em; font-family: arial; padding: 30px; padding-top: 0; padding-bottom: 0;">

<h4>Viewing Arrays and Matrices</h4>


<span>NumPy provides several ways to view arrays and matrices. The shape attribute returns the dimensions of the array. For matrices, the ndim attribute gives the number of dimensions, and the size attribute returns the total number of elements.</span>


</div>

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape) 
print(arr.ndim)  
print(arr.size)

<div style="font-size: 1.1em; font-family: arial; padding: 30px; padding-top: 0; padding-bottom: 0;">

<h4>Manipulating Arrays</h4>


<span>NumPy provides various functions to manipulate arrays, such as slicing, indexing, and concatenation.</span>


</div>

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[2:4])  

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated = np.concatenate((arr1, arr2))
print(concatenated) 

<div style="font-size: 1.1em; font-family: arial; padding: 30px; padding-top: 0; padding-bottom: 0;">

<h4>Standard Deviation and Variance</h4>


<span> standard deviation and variance are statistical measures used to quantify the spread or dispersion of data in an array.</span>


</div>

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(np.std(arr))  
print(np.var(arr))  

<div style="font-size: 1.1em; font-family: arial; padding: 30px; padding-top: 0; padding-bottom: 0;">

<h4>Reshape and Transpose</h4>


<span>The reshape() function allows you to change the shape of an array without modifying its data. The T attribute can be used to transpose a matrix.</span>


</div>

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape((2, 3))
print(reshaped)

matrix = np.array([[1, 2], [3, 4]])
transposed = matrix.T
print(transposed)

<div style="font-size: 1.1em; font-family: arial; padding: 30px; padding-top: 0; padding-bottom: 0;">

<h4>Dot Product vs Element Wise</h4>


<span>The dot product of two arrays can be calculated using the dot() function. Element-wise multiplication can be achieved using the * operator.</span>


</div>

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
dot_product = np.dot(arr1, arr2)
print(dot_product)

element_wise = arr1 * arr2
print(element_wise) 

<div style="font-size: 1.1em; font-family: arial; padding: 30px; padding-top: 0; padding-bottom: 0;">

<h4>Exercise: Nut Butter Store Sales</h4>


<span>In this exercise, let's consider a Nut Butter Store's sales for a week. We'll use NumPy to perform calculations on the sales data.</span>


</div>

In [6]:
np.random.seed(0)
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [7]:
weekly_sales = pd.DataFrame(sales_amounts,
                            index=["Mon", "Tues", "Wed", "Thurs", "Fri"],
                            columns=["Almond butter", "Peanut butter", "Cashew butter"])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [ ]:
prices = np.array([10, 8, 12])
butter_prices = pd.DataFrame(prices.reshape(1, 3),
                             index=["Price"],
                             columns=["Almond butter", "Peanut butter", "Cashew butter"])
butter_prices

<div style="font-size: 1.1em; font-family: arial; padding: 30px; padding-top: 0; padding-bottom: 0;">

<h4>Comparison Operators</h4>


<span>NumPy's comparison operators allow for element-wise comparison of two arrays. Similarly, logical operators perform boolean algebra, which is a branch of algebra that deals with True and False statements.</span>


</div>

In [10]:
array1 = np.array([1, 2, 3])
array2 = np.array([3, 2, 1])


result1 = array1 < array2
print(result1) 

[ True False False]


<div style="font-size: 1.1em; font-family: arial; padding: 30px; padding-top: 0; padding-bottom: 0;">

<h4>Sorting arrays</h4>


<span>Sorting means putting elements in an ordered sequence. Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending. The NumPy ndarray object has a function called sort() , that will sort a specified array.</span>


</div>

In [11]:
random_array = np.random.randint(10, size=(3, 5))
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [12]:
np.sort(random_array)

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]])

In [13]:
np.argsort(random_array)

array([[2, 3, 0, 1, 4],
       [4, 3, 2, 0, 1],
       [2, 3, 0, 4, 1]])